### PR TITLE
simplify error handling

### LINKED ISSUE #6: Suspicious error handling
I have to tell that I'm not absolutely sure about this issue, just sharing the first intuition. I will have to take more detailed look.

It looks to me that error handling is convoluted because a lot of error wrappings that happen throughout the code. Catching error, than wrap it and return the wrapped, than maybe wrap it again, etc. Again, will have to take a deeper look into this problem.

Another thing that bit scares me is the fact that errors are kinda propagated to UI. Yes, I agree that it is reasonable to have a meaningful error message in the UI. But sending a whole error structure bit scares me cause it looks like passing error handling upstream to UI.

https://github.com/eduvpn/eduvpn-common/blob/6229767a7d5b0d3cf3125f2e9da0ca0e66ada814/exports/error.h#L11

Not sure what's the reason for wrapping, but if it is to get the stack trace - this already exists in `errors` package out-of-the-box.

When it comes to passing error messages to UI, I would rather go with error codes. This way UI can do some translation / localization...

Again, will have to take a deeper look to have more articulate suggestion.

### PR DESCRIPTION
**Pull request by peske**
simplify error handling

fixes #6

Signed-off-by: Aleksandar Pesic <peske.nis@gmail.com>

### CODE REVIEW

**Comment by peske** [comment]
Stack trace in errors is implemented by using https://www.bugsnag.com/blog/go-errors

Stack trace can be accessed by using:

```go
fmt.Print(err.(*errors.Error).ErrorStack())
```

This will produce something like:

```
*errors.errorString this function is supposed to crash
/0/go/src/github.com/go-errors/errors/crashy/crashy.go:8 (0x41280)
    Crash: return errors.New(Crashed)
/0/go/src/github.com/go-errors/errors/example/main.go:11 (0x2026)
    main: err := crashy.Crash()
```

Note that the format can be simply customized as needed.

The only thing that needs to be ensured is that all our functions and methods are returning errors of type `errors.Error` (from https://www.bugsnag.com/blog/go-errors package). When we get an error from some external library, we should *wrap* it into `errors.Error` type. But this should be done **only once**, without wrapping it again and again upstream. Here's an example:

```go
func read(file string) ([]byte, error) {
    data, err := os.ReadFile(file)
    // Wrap simple
    if err != nil {
        return nil, errors.Wrap(err, 0)
    }
    // Wrap with prefix
    if err != nil {
        return nil, errors.WrapPrefix(err, "my prefix", 0)
    }
    return data, nil
}
```

**Comment by peske** [comment]
I also want to explain something about custom error types. We had quite a few defined in the project. Probably more than dozen, maybe even ~20. And wast majority of them are actually not used at all, except for generating the error message. There's a rule in software development that says "**don't develop functionality which is not used**". It just complicates code, and makes understanding and maintaining the code harder. For this reason I've removed all these custom error types, and left only three of them which are actually used. One that I've left is

https://github.com/eduvpn/eduvpn-common/blob/5143ed35f2af2fe0e725c2a466c86f1cf929333c/internal/oauth/oauth.go#L549

It is used in determining *error level*. Actually this is the only error type that had `ErrorInfo` assigned to it. All other errors were resulting in level `ErrorOther`. The other error type that I've kept is used in OAuth retry. (I can't remember the error type name at moment.)

So the key things are:

- We are not using these additional types internally for any other reason besides generating error message, and we don't need custom types for that.
- All these types were defined in `internal `directory, meaning that they weren't accessible to external code that may use our library. Even if these types were in some public packages, I doubt that they would be useful to the external code.

If in the future it turns out that we need some error types, it will be **very easy** to create them (only few lines of code per type). But we should do that **only when they are actually needed, and will be used**. Not in advance.

**Comment by peske** [comment]
Finally, I've changed one more thing - variable names. I've tried to shorten the names (1-4 chars) wherever possible. This is also according to Golang style guide. Also, for almost all variables is very obvious what's the purpose because they are usually defined only few lines above their usage, so everyone can quickly see the purpose even if the name isn't obvious. I didn't do that for function arguments though.

**Comment by jwijenbergh** [comment]
These changes have been incorporated into the main branch (couldn't merge directly due to conflicts). Relevant commit 3ac1d35257b56cca92ad0eb7f4d18abb366cf105

**Pull request closed without merging**
